config/routes.rb
Flix::Application.routes.draw do
  root 'movies#index'
  #get 'movies' => 'movies#index'
  #get 'movies/:id' => 'movies#show', as: 'movie'
  #get 'movies/:id/edit' => 'movies#edit', as: 'edit_movie'
  #patch 'movies/:id' => 'movies#update'
  resources :movies do
    resources :reviews
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  RATINGS = %w(G PG PG-13 R NC-17)
  CULT_CLASSIC_REVIEW_SIZE = 50
  CULT_CLASSIC_REVIEW_AVERAGE_STARS = 4

  has_many :reviews, dependent: :destroy

  has_attached_file :image, styles: {
    small: "90x133>",
    thumb: "50x50>"
  }

  validates :title, :released_on, :duration, presence: true
  validates :description, length: {minimum: 25}
  validates :total_gross, numericality: {greater_than_or_equal_to: 0}
  validates :image_file_name, allow_blank: true, format: {
      with:    /\w+.(gif|jpg|png)\z/i,
      message: "must reference a GIF, JPG, or PNG image"
    }
  validates_attachment :image,
    :content_type => { :content_type => ['image/jpeg', 'image/png'] },
    :size => { :less_than => 1.megabyte }
  validates :rating, inclusion: {in: RATINGS}

  def flop?
    (total_gross.blank? || total_gross < 50000000) && !cult_classic?
  end

  def cult_classic?
    reviews.size >= CULT_CLASSIC_REVIEW_SIZE && average_stars >= CULT_CLASSIC_REVIEW_AVERAGE_STARS
  end

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end

  def average_stars
    reviews.average :stars
  end

  def recent_reviews
    reviews.order("created_at desc").limit 2
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  STARS = [1, 2, 3, 4, 5]

  validates :name, presence: true
  validates :comment, length: {minimum: 4}
  validates :stars, inclusion: {
    in: STARS,
    message: "must be between 1 and 5"
  }

  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.released
  end

  def show
    @movie = Movie.find params[:id]
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    if @movie.update movie_params
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new movie_params
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find params[:id]
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end

  def movie_params
    params.require(:movie).permit :title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image
  end

  private :movie_params
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_movie

  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new review_params
    if @review.save
      redirect_to movie_reviews_path(@movie), notice: "Thanks for your review!"
    else
      render :new
    end
  end

  def edit
    @review = @movie.reviews.find params[:id]
  end

  def update
    @review = @movie.reviews.find params[:id]
    if @review.update review_params
      redirect_to movie_reviews_path(@movie), notice: "Review successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    review = @movie.reviews.find params[:id]
    review.destroy
    redirect_to movie_reviews_url(@movie), alert: "Review successfully deleted!"
  end

  def review_params
    params.require(:review).permit :name, :stars, :comment
  end

  def set_movie
    @movie = Movie.find params[:movie_id]
  end

  private :set_movie, :review_params
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def format_total_gross(movie)
    if movie.flop?
      content_tag :strong, "Flop!"
    else
      number_to_currency movie.total_gross
    end
  end

  def image_for(movie)
    if movie.image.exists?
      image_tag movie.image.url(:small)
    else
      image_tag 'placeholder.png'
    end
  end

  def format_average_stars(movie)
    if movie.average_stars.nil?
      content_tag :strong, 'No reviews'
    else
      '*'*movie.average_stars + ' ' + pluralize(number_with_precision(movie.average_stars, precision: 1), 'star')
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2013
    <%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
  </p>
  <p>
    For educational purposes only.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">

  <%= render 'layouts/flashes' %>

  <div id="container">
    <section id="sidebar">
      <%= render "layouts/sidebar" %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <%= render 'shared/errors', object: @movie %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :rating %>
        <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
      </li>
      <li class="required">
        <%= f.label :released_on %>
        <%= f.date_field :released_on %>
      </li>
      <li class="required">
        <%= f.label :total_gross %>
        <%= f.number_field :total_gross %>
      </li>
      <li class="required">
        <%= f.label :duration %>
        <%= f.text_field :duration, size: 10 %>
      </li>
      <li>
        <%= f.label :cast %>
        <%= f.text_field :cast %>
      </li>
      <li>
        <%= f.label :director %>
        <%= f.text_field :director %>
      </li>
      <li>
        <%= f.label :image %>
        <%= f.file_field :image %>
      </li>
      <li>
        <%= image_for(@movie) %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", movies_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/movies/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @movie.title %></h1>
</header>

<%= render 'form' %>

app/views/movies/index.html.erb
<ul id="movies">
  <% @movies.each do |movie| %>
    <li>
      <article class="movie">
        <header>
          <%= image_for(movie) %>
          <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
          <h3><%= movie.cast %></h3>
        </header>
        <p>
          <%= truncate(movie.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Rating</th>
            <td><%= movie.rating %></td>
          </tr>
          <tr>
            <th>Duration</th>
            <td><%= movie.duration %></td>
          </tr>
          <tr>
            <th>Total Gross</th>
            <td><%= format_total_gross(movie) %></td>
          </tr>
        </table>
        <footer>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<header id="content-header">
  <h1>Create a New Movie</h1>
</header>

<%= render 'form' %>

app/views/movies/show.html.erb
<article id="movie" class="movie">
  <header>
    <%= image_for(@movie) %>
    <h1><%= @movie.title %></h1>
    <h2>Released: <%= @movie.released_on %></h2>
  </header>

  <p>
    <%= @movie.description %>
  </p>

  <h3 class="no-rule">
    <%= @movie.rating %> &bull; <%= @movie.duration %>
  </h3>

  <h3>Average Review</h3>
  <p>
    <%= format_average_stars(@movie) %>
  </p>

  <h3>Cast</h3>
  <p>
    <%= @movie.cast %>
  </p>

  <h3>Director</h3>
  <p>
    <%= @movie.director %>
  </p>

  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>

  <% if @movie.recent_reviews.any? %>
    <h3>Reviews</h3>
    <%= render 'reviews/list', reviews: @movie.recent_reviews, with_delete: false %>
    <p>
      Read all <%= link_to pluralize(@movie.reviews.size, "review"), movie_reviews_path(@movie) %>
    </p>
  <% end %>

  <footer>
    <%= link_to "Write Review", new_movie_review_path(@movie), class: 'button ok review' %>
    <nav>
      <%= link_to 'Edit', edit_movie_path(@movie), class: 'button' %>
      <%= link_to 'Delete', @movie,
                   class: 'button',
                   method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </footer>
</article>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <%= render 'shared/errors', object: @review %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required stars">
        <%= f.label :stars %>
        <% Review::STARS.each do |star| %>
          <span class="star">
            <%= f.radio_button :stars, star %> <%= star %>
          </span>
        <% end %>
      </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", @movie, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/reviews/_list.html.erb
<ol id="reviews">
  <% reviews.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.stars, 'star') %></span>
      <span class="user">by <%= review.name %></span>
      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
      <% if with_delete %>
        <%= link_to "Edit",
                    edit_movie_review_path(@movie, review),
                    id: "edit_review_#{review.id}",
                    class: "button small"%>
        <%= link_to "Delete",
                    movie_review_path(@movie, review),
                    id: "delete_review_#{review.id}",
                    class: "button small",
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/reviews/edit.html.erb
<header id="content-header">
  <h1>Edit Review by <%= @review.name %> for <%= link_to(@movie.title, @movie) %></h1>
</header>

<%= render 'form' %>

app/views/reviews/index.html.erb
<header id="content-header">
  <h1>Reviews for <%= link_to(@movie.title, @movie) %></h1>
</header>

<%= render 'reviews/list', reviews: @reviews, with_delete: true %>

app/views/reviews/new.html.erb
<header id="content-header">
  <h1>New Review for <%= link_to(@movie.title, @movie) %></h1>
</header>

<%= render 'form' %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>